In [80]:
# 라이브러리 불러오기
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# 머신러닝
# 교자검증
from sklearn.model_selection import cross_val_score
# 분리
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [81]:
train = pd.read_csv("./data/train.csv", index_col='no')
# train
test = pd.read_csv("./data/test.csv", index_col='no')
# test

In [82]:
train['workclass'].unique()

# 데이터 앞에 공백이 있다

array([' Private', ' Self-emp-not-inc', ' Local-gov', ' ?', ' State-gov',
       ' Self-emp-inc', ' Federal-gov', ' Without-pay', ' Never-worked'],
      dtype=object)

In [83]:
# 문자열 데이터 앞 공백 제거
df = train[['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']]
df = df.apply(lambda x: x.str.lstrip(), axis=1)
train[['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']] = df

df = test[['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']]
df = df.apply(lambda x: x.str.lstrip(), axis=1)
test[['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']] = df

In [84]:
train['workclass'].unique()
test['workclass'].unique()

# 공백 없앰

array(['Private', 'Self-emp-not-inc', 'Local-gov', '?', 'State-gov',
       'Self-emp-inc', 'Federal-gov', 'Without-pay', 'Never-worked'],
      dtype=object)

array(['?', 'Private', 'Self-emp-not-inc', 'Local-gov', 'Self-emp-inc',
       'State-gov', 'Federal-gov', 'Without-pay', 'Never-worked'],
      dtype=object)

In [85]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29305 entries, 1 to 29305
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             29305 non-null  int64 
 1   workclass       29305 non-null  object
 2   fnlwgt          29305 non-null  int64 
 3   education       29305 non-null  object
 4   education-num   29305 non-null  int64 
 5   marital-status  29305 non-null  object
 6   occupation      29305 non-null  object
 7   relationship    29305 non-null  object
 8   race            29305 non-null  object
 9   sex             29305 non-null  object
 10  capital-gain    29305 non-null  int64 
 11  capital-loss    29305 non-null  int64 
 12  hours-per-week  29305 non-null  int64 
 13  native-country  29305 non-null  object
 14  income          29305 non-null  int64 
dtypes: int64(7), object(8)
memory usage: 3.6+ MB


In [86]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19537 entries, 29306 to 48842
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             19537 non-null  int64 
 1   workclass       19537 non-null  object
 2   fnlwgt          19537 non-null  int64 
 3   education       19537 non-null  object
 4   education-num   19537 non-null  int64 
 5   marital-status  19537 non-null  object
 6   occupation      19537 non-null  object
 7   relationship    19537 non-null  object
 8   race            19537 non-null  object
 9   sex             19537 non-null  object
 10  capital-gain    19537 non-null  int64 
 11  capital-loss    19537 non-null  int64 
 12  hours-per-week  19537 non-null  int64 
 13  native-country  19537 non-null  object
dtypes: int64(6), object(8)
memory usage: 2.2+ MB


In [87]:
# int
train['age'].unique()
train['fnlwgt'].unique()
train['education-num'].unique()
train['capital-gain'].unique()
train['capital-loss'].unique()
train['hours-per-week'].unique()

# Object
train['education'].unique()
train['marital-status'].unique()
train['relationship'].unique()
train['race'].unique()
train['sex'].unique()


# '?' 있는 컬럼
train['workclass'].unique()
train['occupation'].unique()
train['native-country'].unique()


array([25, 39, 35, 64, 24, 66, 56, 70, 21, 33, 45, 54, 63, 58, 44, 31, 17,
       43, 18, 23, 50, 19, 38, 29, 30, 47, 28, 22, 59, 34, 49, 36, 32, 46,
       42, 61, 40, 26, 57, 27, 41, 37, 60, 48, 62, 53, 68, 75, 20, 51, 73,
       69, 72, 65, 76, 52, 55, 74, 90, 67, 78, 80, 77, 71, 81, 83, 82, 79,
       85, 87, 84, 88, 86, 89], dtype=int64)

array([219199,  52978, 196899, ..., 100605, 372636, 258474], dtype=int64)

array([ 7, 10, 13, 11,  5,  9, 14,  3, 15,  8,  6, 12, 16,  4,  2,  1],
      dtype=int64)

array([    0, 99999,  1151,  2176, 14084,  3325,  3103,  2174,  8614,
       27828, 14344, 15024,  2463,  3137,   594,  5178,  3942,  2354,
        7688, 20051,  2290,  3674,  6849,  3418,  4934,  2202,  5455,
       13550,  5013,  4101,  2907,  7298,  7430,  4650,  2885,  2829,
        4386,  2977,   401,  4064,  1424,  2635,  4787,  2105,  2964,
        9386,  6497, 10520,  1055, 10566,  3464, 15020,  4416,  1409,
        6767,  1086,  3818,  2050,  3471,  7896,  3781,  3908,  6097,
        4508,  3411,  1506, 15831,  1173,  3273,  6418,  2329, 34095,
        3887,  2936,  7443,   914,  1471,   991,  1797,  2036,  5721,
        2597,  4865,  4931,  2228,  6612,  2414,  2346,  6514,   114,
        4687,  2407,  5060,  2538,  1848, 11678,  2993, 41310,  2653,
       10605,  2580,  1264,  2009, 25236,  1831,  1455,  7978,  6360,
        6723, 25124,  3456,  1111,  3432,  2961,  5556, 22040, 18481],
      dtype=int64)

array([   0, 1721, 1741, 1590, 1902, 1138,  625, 2057, 1887, 1848, 1977,
       2339, 1602, 1564, 1579, 2205, 2001, 2415, 1628, 1672, 1092, 2444,
       1719, 1980, 2377, 1408, 2258, 1504, 2051, 2392, 1669, 2174, 1485,
        213, 2352, 1668, 2824, 3004, 1876, 2559, 2246, 1740,  880, 1340,
       1825, 1726, 1573, 1974, 4356, 1411, 2002, 1648, 2472, 2179, 2206,
       2042, 1380, 2267, 1651, 1258, 1844, 2149, 1762,  810, 1594, 1617,
        974, 2238, 2129, 1816, 1510, 2231, 1755, 2547,  323,  653, 2603,
       2457, 1429, 1735, 2467, 3175, 1944, 2201,  419, 1870, 1539, 3683,
       2163, 2465, 3770], dtype=int64)

array([40, 55, 50, 70, 25, 35, 29, 37, 45, 15, 16, 30, 20, 60, 65, 10, 80,
       24, 36, 12, 66,  6, 42, 56, 44, 48, 32, 99, 52, 39,  8,  2, 47, 54,
       89,  1, 34, 53, 38, 33, 90, 43, 46, 14,  9,  4, 62, 28, 17, 64, 75,
       49, 21,  3, 22, 18, 58, 27, 41, 13, 72, 98, 96, 84,  7, 26, 77,  5,
       31, 63, 92, 51, 85, 57, 67, 23, 19, 68, 11, 59, 81, 61, 88, 74, 86,
       78, 69, 91, 82, 76, 97, 94, 73], dtype=int64)

array(['11th', 'Some-college', 'Bachelors', 'Assoc-voc', '9th', 'HS-grad',
       'Masters', '5th-6th', 'Prof-school', '12th', '10th', 'Assoc-acdm',
       'Doctorate', '7th-8th', '1st-4th', 'Preschool'], dtype=object)

array(['Divorced', 'Never-married', 'Married-civ-spouse', 'Separated',
       'Married-spouse-absent', 'Widowed', 'Married-AF-spouse'],
      dtype=object)

array(['Not-in-family', 'Husband', 'Unmarried', 'Other-relative',
       'Own-child', 'Wife'], dtype=object)

array(['White', 'Asian-Pac-Islander', 'Black', 'Amer-Indian-Eskimo',
       'Other'], dtype=object)

array(['Male', 'Female'], dtype=object)

array(['Private', 'Self-emp-not-inc', 'Local-gov', '?', 'State-gov',
       'Self-emp-inc', 'Federal-gov', 'Without-pay', 'Never-worked'],
      dtype=object)

array(['Machine-op-inspct', 'Other-service', 'Handlers-cleaners',
       'Tech-support', 'Transport-moving', 'Farming-fishing',
       'Prof-specialty', 'Priv-house-serv', 'Adm-clerical',
       'Protective-serv', 'Exec-managerial', '?', 'Craft-repair', 'Sales',
       'Armed-Forces'], dtype=object)

array(['United-States', 'Haiti', 'Mexico', 'Puerto-Rico', 'Philippines',
       '?', 'Germany', 'Peru', 'Ecuador', 'Iran', 'Thailand',
       'Dominican-Republic', 'Poland', 'Scotland', 'Italy', 'Jamaica',
       'China', 'Portugal', 'Columbia', 'Hungary', 'Vietnam', 'Taiwan',
       'Canada', 'Hong', 'Guatemala', 'El-Salvador', 'England',
       'Outlying-US(Guam-USVI-etc)', 'India', 'France', 'Cuba', 'Greece',
       'Trinadad&Tobago', 'South', 'Japan', 'Yugoslavia', 'Nicaragua',
       'Ireland', 'Cambodia', 'Laos', 'Honduras', 'Holand-Netherlands'],
      dtype=object)

In [88]:
train.corr()

age    fnlwgt  education-num  capital-gain  capital-loss  \
age             1.000000 -0.075753       0.035084      0.078498      0.054413   
fnlwgt         -0.075753  1.000000      -0.030600     -0.005051     -0.001513   
education-num   0.035084 -0.030600       1.000000      0.127651      0.083925   
capital-gain    0.078498 -0.005051       0.127651      1.000000     -0.031401   
capital-loss    0.054413 -0.001513       0.083925     -0.031401      1.000000   
hours-per-week  0.073100 -0.010154       0.147569      0.088609      0.055271   
income          0.238460 -0.002994       0.331798      0.221387      0.135645   

                hours-per-week    income  
age                   0.073100  0.238460  
fnlwgt               -0.010154 -0.002994  
education-num         0.147569  0.331798  
capital-gain          0.088609  0.221387  
capital-loss          0.055271  0.135645  
hours-per-week        1.000000  0.231045  
income                0.231045  1.000000

In [89]:
train['education'].unique()

array(['11th', 'Some-college', 'Bachelors', 'Assoc-voc', '9th', 'HS-grad',
       'Masters', '5th-6th', 'Prof-school', '12th', '10th', 'Assoc-acdm',
       'Doctorate', '7th-8th', '1st-4th', 'Preschool'], dtype=object)

In [90]:
temp = train['education'].value_counts()
temp

HS-grad         9435
Some-college    6558
Bachelors       4848
Masters         1587
Assoc-voc       1230
11th            1057
Assoc-acdm       980
10th             816
7th-8th          574
Prof-school      500
9th              430
12th             415
Doctorate        347
5th-6th          334
1st-4th          148
Preschool         46
Name: education, dtype: int64

In [91]:
for i in range(len(temp)):
    print(f"\'{temp.index[i]}\':")

'HS-grad':
'Some-college':
'Bachelors':
'Masters':
'Assoc-voc':
'11th':
'Assoc-acdm':
'10th':
'7th-8th':
'Prof-school':
'9th':
'12th':
'Doctorate':
'5th-6th':
'1st-4th':
'Preschool':


In [92]:
pt_edu = train.pivot_table(values='income', #데이터로 사용 할 컬럼 지정
                index=['education'], # 데이터 요약시 확인하고 싶은 컬럼
                aggfunc='mean' ) 
pt_edu = pt_edu.sort_values(by='income', ascending=False)
pt_edu

income
education             
Prof-school   0.750000
Doctorate     0.740634
Masters       0.543793
Bachelors     0.412129
Assoc-acdm    0.259184
Assoc-voc     0.256911
Some-college  0.191674
HS-grad       0.160042
7th-8th       0.076655
12th          0.065060
11th          0.057711
9th           0.053488
10th          0.051471
5th-6th       0.047904
1st-4th       0.013514
Preschool     0.000000

In [93]:
dict_edu = {
    'HS-grad':16,
    'Some-college':19,
    'Bachelors':41,
    'Masters':54,
    'Assoc-voc':26,
    '11th':6,
    'Assoc-acdm':26,
    '10th':5,
    '7th-8th':8,
    'Prof-school':75,
    '9th':5,
    '12th':7,
    'Doctorate':74,
    '5th-6th':5,
    '1st-4th':1,
    'Preschool':0
}

In [94]:
train['education'] = train['education'].map(dict_edu)
test['education'] = test['education'].map(dict_edu)

In [95]:
train['education'].unique()

array([ 6, 19, 41, 26,  5, 16, 54, 75,  7, 74,  8,  1,  0], dtype=int64)

In [96]:
test['education'].unique()

array([19, 16, 41, 74,  5, 26, 54,  8,  6, 75,  7,  1,  0], dtype=int64)

In [97]:
temp = train['marital-status'].value_counts()
temp

Married-civ-spouse       13331
Never-married             9673
Divorced                  4030
Widowed                    942
Separated                  914
Married-spouse-absent      394
Married-AF-spouse           21
Name: marital-status, dtype: int64

In [98]:
for i in range(len(temp)):
    print(f"\'{temp.index[i]}\':")

'Married-civ-spouse':
'Never-married':
'Divorced':
'Widowed':
'Separated':
'Married-spouse-absent':
'Married-AF-spouse':


In [99]:
pt_marry = train.pivot_table(values='income', #데이터로 사용 할 컬럼 지정
                index=['marital-status'], # 데이터 요약시 확인하고 싶은 컬럼
                aggfunc='mean' ) 
pt_marry = pt_marry.sort_values(by='income', ascending=False)
pt_marry

income
marital-status                 
Married-civ-spouse     0.448954
Married-AF-spouse      0.380952
Divorced               0.104467
Married-spouse-absent  0.093909
Widowed                0.083864
Separated              0.067834
Never-married          0.046831

In [100]:
dict_marry = {
    'Married-civ-spouse':45,
    'Never-married':5,
    'Divorced':10,
    'Widowed':8,
    'Separated':7,
    'Married-spouse-absent':9,
    'Married-AF-spouse':38
}

In [101]:
train['marital-status'] = train['marital-status'].map(dict_marry)
test['marital-status'] = test['marital-status'].map(dict_marry)

In [102]:
train['marital-status'].unique()

array([10,  5, 45,  7,  9,  8, 38], dtype=int64)

In [103]:
test['marital-status'].unique()

array([ 5, 45,  8, 10,  7,  9, 38], dtype=int64)

In [104]:
temp = train['relationship'].value_counts()
temp

Husband           11769
Not-in-family      7637
Own-child          4554
Unmarried          3071
Wife               1370
Other-relative      904
Name: relationship, dtype: int64

In [105]:
for i in range(len(temp)):
    print(f"\'{temp.index[i]}\':")

'Husband':
'Not-in-family':
'Own-child':
'Unmarried':
'Wife':
'Other-relative':


In [106]:
pt_rel = train.pivot_table(values='income', #데이터로 사용 할 컬럼 지정
                index=['relationship'], # 데이터 요약시 확인하고 싶은 컬럼
                aggfunc='mean' ) 
pt_rel = pt_rel.sort_values(by='income', ascending=False)
pt_rel

income
relationship            
Wife            0.466423
Husband         0.452035
Not-in-family   0.105146
Unmarried       0.060567
Other-relative  0.035398
Own-child       0.014273

In [107]:
dict_rel = {
    'Husband':45,
    'Not-in-family':11,
    'Own-child':1,
    'Unmarried':6,
    'Wife':47,
    'Other-relative':4
}

In [108]:
train['relationship'] = train['relationship'].map(dict_rel)
test['relationship'] = test['relationship'].map(dict_rel)

In [109]:
train['relationship'].unique()

array([11, 45,  6,  4,  1, 47], dtype=int64)

In [110]:
test['relationship'].unique()

array([ 1, 47, 45, 11,  6,  4], dtype=int64)

In [111]:
temp = train['race'].value_counts()
temp

White                 25081
Black                  2776
Asian-Pac-Islander      919
Amer-Indian-Eskimo      290
Other                   239
Name: race, dtype: int64

In [112]:
for i in range(len(temp)):
    print(f"\'{temp.index[i]}\':")

'White':
'Black':
'Asian-Pac-Islander':
'Amer-Indian-Eskimo':
'Other':


In [113]:
pt_race = train.pivot_table(values='income', #데이터로 사용 할 컬럼 지정
                index=['race'], # 데이터 요약시 확인하고 싶은 컬럼
                aggfunc='mean' ) 
pt_race = pt_race.sort_values(by='income', ascending=False)
pt_race

income
race                        
White               0.255851
Asian-Pac-Islander  0.255713
Amer-Indian-Eskimo  0.124138
Black               0.118516
Other               0.117155

In [114]:
dict_race = {
    'White':256,
    'Black':118,
    'Asian-Pac-Islander':256,
    'Amer-Indian-Eskimo':124,
    'Other':117
}

In [115]:
train['race'] = train['race'].map(dict_race)
test['race'] = test['race'].map(dict_race)

In [116]:
train['race'].unique()

array([256, 118, 124, 117], dtype=int64)

In [117]:
test['race'].unique()

array([256, 118, 124, 117], dtype=int64)

In [118]:
temp = train['sex'].value_counts()
temp

Male      19621
Female     9684
Name: sex, dtype: int64

In [119]:
for i in range(len(temp)):
    print(f"\'{temp.index[i]}\':")

'Male':
'Female':


In [120]:
pt_sex = train.pivot_table(values='income', #데이터로 사용 할 컬럼 지정
                index=['sex'], # 데이터 요약시 확인하고 싶은 컬럼
                aggfunc='mean' ) 
pt_sex = pt_sex.sort_values(by='income', ascending=False)
pt_sex

income
sex             
Male    0.305132
Female  0.109252

In [121]:
dict_sex = {
    'Male':3,
    'Female':1
}

In [122]:
train['sex'] = train['sex'].map(dict_sex)
test['sex'] = test['sex'].map(dict_sex)

In [123]:
train['sex'].unique()

array([3, 1], dtype=int64)

In [124]:
test['sex'].unique()

array([3, 1], dtype=int64)

In [125]:
####################################################
##########비상비상비상###############################
####################################################

In [141]:
temp = train['workclass'].value_counts()
temp

Private             20410
Self-emp-not-inc     2305
Local-gov            1868
?                    1663
State-gov            1201
Self-emp-inc          987
Federal-gov           854
Without-pay            12
Never-worked            5
Name: workclass, dtype: int64

In [142]:
for i in range(len(temp)):
    print(f"\'{temp.index[i]}\':")

'Private':
'Self-emp-not-inc':
'Local-gov':
'?':
'State-gov':
'Self-emp-inc':
'Federal-gov':
'Without-pay':
'Never-worked':


In [143]:
pt_wc = train.pivot_table(values='income', #데이터로 사용 할 컬럼 지정
                index=['workclass'], # 데이터 요약시 확인하고 싶은 컬럼
                aggfunc='mean' ) 
pt_wc = pt_wc.sort_values(by='income', ascending=False)
pt_wc

income
workclass                 
Self-emp-inc      0.554205
Federal-gov       0.382904
Local-gov         0.299251
Self-emp-not-inc  0.278959
State-gov         0.262281
Private           0.219402
?                 0.105232
Without-pay       0.083333
Never-worked      0.000000

In [144]:
dict_wc = {
    'Private':22,
    'Self-emp-not-inc':28,
    'Local-gov':30,
    '?':11,
    'State-gov':26,
    'Self-emp-inc':55,
    'Federal-gov':38,
    'Without-pay':8,
    'Never-worked':0
}

In [145]:
train['workclass'] = train['workclass'].map(dict_wc)
test['workclass'] = test['workclass'].map(dict_wc)

In [151]:
train['workclass'].unique()

array([22, 28, 30, 26, 55, 38,  8,  0], dtype=int64)

In [152]:
test['workclass'].unique()

array([11, 22, 28, 30, 55, 26, 38,  8,  0], dtype=int64)

In [148]:
#==========================================================================================================================================================
#==========================================================================================================================================================
#==========================================================================================================================================================

train['workclass'].unique()
train['workclass'][train['workclass']!=11]

w_train = train.loc[train['workclass']!=11]

wX_train = w_train[['age', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income']]
wy_train = train['workclass'][train['workclass']!=11]

w_train2 =  train.loc[train['workclass']==11]
wX_test = w_train2[['age', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income']]

print(wX_train.shape)
print(wy_train.shape)
print(wX_test.shape)

wX_train = pd.get_dummies(wX_train)
wX_test = pd.get_dummies(wX_test)

print(wX_train.shape)
print(wy_train.shape)
print(wX_test.shape)

from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(random_state=7)
gb.fit(wX_train, wy_train)

res = cross_val_score(gb,wX_train,wy_train,cv=8)
res.mean()

array([22, 28, 30, 11, 26, 55, 38,  8,  0], dtype=int64)

no
1        22
2        22
3        22
4        22
5        22
         ..
29300    22
29301    22
29302    22
29303    28
29304    22
Name: workclass, Length: 27642, dtype: int64

(27642, 13)
(27642,)
(1663, 13)
(27642, 13)
(27642,)
(1663, 13)


GradientBoostingClassifier(random_state=7)

0.7381882679758268

In [150]:
pt1 = gb.predict(wX_test)
train['workclass'][train['workclass']==11] = pt1
# train['workclass'] = train['workclass'].astype('int64')
train['workclass'].unique()

ValueError: cannot set using a list-like indexer with a different length than the value

In [153]:
w_train = test.loc[test['workclass']!=11]

wX_train = w_train[['age', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country']]
wy_train = test['workclass'][test['workclass']!=11]

w_train2 =  test.loc[test['workclass']==11]
wX_test = w_train2[['age', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country']]

print(wX_train.shape)
print(wy_train.shape)
print(wX_test.shape)


wX_train = pd.get_dummies(wX_train)
wX_test = pd.get_dummies(wX_test)

print(wX_train.shape)
print(wy_train.shape)
print(wX_test.shape)

gb = GradientBoostingClassifier(random_state=7)
gb.fit(wX_train, wy_train)

res = cross_val_score(gb,wX_train,wy_train,cv=8)
res.mean()

(18401, 12)
(18401,)
(1136, 12)
(18401, 12)
(18401,)
(1136, 12)


GradientBoostingClassifier(random_state=7)

0.7312647147742948

In [154]:
pt1 = gb.predict(wX_test)
test['workclass'][test['workclass']==11] = pt1
# test['workclass'] = test['workclass'].astype('int64')
test['workclass'].unique()

#==========================================================================================================================================================
#==========================================================================================================================================================
#==========================================================================================================================================================


array([22, 28, 30, 55, 26, 38,  8,  0], dtype=int64)

In [126]:
temp = train['occupation'].value_counts()
temp

Prof-specialty       3724
Craft-repair         3632
Exec-managerial      3609
Adm-clerical         3440
Sales                3292
Other-service        2975
Machine-op-inspct    1811
?                    1668
Transport-moving     1393
Handlers-cleaners    1249
Farming-fishing       888
Tech-support          865
Protective-serv       603
Priv-house-serv       146
Armed-Forces           10
Name: occupation, dtype: int64

In [127]:
for i in range(len(temp)):
    print(f"\'{temp.index[i]}\':")

'Prof-specialty':
'Craft-repair':
'Exec-managerial':
'Adm-clerical':
'Sales':
'Other-service':
'Machine-op-inspct':
'?':
'Transport-moving':
'Handlers-cleaners':
'Farming-fishing':
'Tech-support':
'Protective-serv':
'Priv-house-serv':
'Armed-Forces':


In [128]:
pt_oc = train.pivot_table(values='income', #데이터로 사용 할 컬럼 지정
                index=['occupation'], # 데이터 요약시 확인하고 싶은 컬럼
                aggfunc='mean' ) 
pt_oc = pt_oc.sort_values(by='income', ascending=False)
pt_oc

income
occupation                 
Exec-managerial    0.481851
Prof-specialty     0.448980
Protective-serv    0.321725
Armed-Forces       0.300000
Tech-support       0.284393
Sales              0.275516
Craft-repair       0.225771
Transport-moving   0.202441
Adm-clerical       0.133140
Machine-op-inspct  0.131971
Farming-fishing    0.106982
?                  0.104916
Handlers-cleaners  0.066453
Other-service      0.043361
Priv-house-serv    0.020548

In [129]:
dict_oc = {
    'Prof-specialty':45,
    'Craft-repair':23,
    'Exec-managerial':48,
    'Adm-clerical':13,
    'Sales':28,
    'Other-service':4,
    'Machine-op-inspct':13,
    '?':10,
    'Transport-moving':20,
    'Handlers-cleaners':7,
    'Farming-fishing':11,
    'Tech-support':28,
    'Protective-serv':32,
    'Priv-house-serv':2,
    'Armed-Forces':30
}

In [130]:
train['occupation'] = train['occupation'].map(dict_oc)
test['occupation'] = test['occupation'].map(dict_oc)

In [131]:
train['occupation'].unique()

array([13,  4,  7, 28, 20, 11, 45,  2, 32, 48, 10, 23, 30], dtype=int64)

In [132]:
test['occupation'].unique()

array([10,  4, 28, 48, 11, 13, 23,  7, 32, 45, 20,  2, 30], dtype=int64)

In [133]:
temp = train['native-country'].unique()
temp


array(['United-States', 'Haiti', 'Mexico', 'Puerto-Rico', 'Philippines',
       '?', 'Germany', 'Peru', 'Ecuador', 'Iran', 'Thailand',
       'Dominican-Republic', 'Poland', 'Scotland', 'Italy', 'Jamaica',
       'China', 'Portugal', 'Columbia', 'Hungary', 'Vietnam', 'Taiwan',
       'Canada', 'Hong', 'Guatemala', 'El-Salvador', 'England',
       'Outlying-US(Guam-USVI-etc)', 'India', 'France', 'Cuba', 'Greece',
       'Trinadad&Tobago', 'South', 'Japan', 'Yugoslavia', 'Nicaragua',
       'Ireland', 'Cambodia', 'Laos', 'Honduras', 'Holand-Netherlands'],
      dtype=object)

In [134]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [135]:
# for i in range(len(temp)):
#     print(f"\'{temp[i]}\':")

In [136]:
pt_nc = train.pivot_table(values='income', #데이터로 사용 할 컬럼 지정
                index=['native-country'], # 데이터 요약시 확인하고 싶은 컬럼
                aggfunc='mean' ) 
pt_nc = pt_nc.sort_values(by='income', ascending=False)
pt_nc

income
native-country                      
India                       0.433333
Hungary                     0.416667
Japan                       0.388889
England                     0.373333
Canada                      0.369369
Iran                        0.368421
Italy                       0.366667
Greece                      0.360000
Ireland                     0.347826
Germany                     0.330645
Cambodia                    0.315789
Taiwan                      0.307692
Yugoslavia                  0.307692
France                      0.300000
Philippines                 0.280899
China                       0.264706
United-States               0.245884
?                           0.236364
Cuba                        0.223404
Hong                        0.210526
Ecuador                     0.190476
South                       0.189189
Portugal                    0.162791
Poland                      0.150943
Thailand                    0.133333
Jamaica                     0.132353
Peru                        0.120000
Scotland                    0.111111
Puerto-Rico                 0.102564
Honduras                    0.090909
Haiti                       0.078431
Laos                        0.076923
Outlying-US(Guam-USVI-etc)  0.066667
Mexico                      0.053541
El-Salvador                 0.052083
Dominican-Republic          0.049180
Guatemala                   0.039216
Columbia                    0.037736
Nicaragua                   0.035714
Vietnam                     0.020000
Trinadad&Tobago             0.000000
Holand-Netherlands          0.000000

In [137]:
dict_nc = {
    'United-States':25,
    'Haiti':8,
    'Mexico':5,
    'Puerto-Rico':10,
    'Philippines':28,
    '?':24,
    'Germany':33,
    'Peru':12,
    'Ecuador':19,
    'Iran':37,
    'Thailand':13,
    'Dominican-Republic':5,
    'Poland':15,
    'Scotland':11,
    'Italy':37,
    'Jamaica':13,
    'China':26,
    'Portugal':16,
    'Columbia':4,
    'Hungary':42,
    'Vietnam':2,
    'Taiwan':31,
    'Canada':37,
    'Hong':21,
    'Guatemala':4,
    'El-Salvador':5,
    'England':37,
    'Outlying-US(Guam-USVI-etc)':7,
    'India':43,
    'France':30,
    'Cuba':22,
    'Greece':36,
    'Trinadad&Tobago':0,
    'South':19,
    'Japan':39,
    'Yugoslavia':31,
    'Nicaragua':4,
    'Ireland':35,
    'Cambodia':32,
    'Laos':8,
    'Honduras':9,
    'Holand-Netherlands':0
}

In [138]:
train['native-country'] = train['native-country'].map(dict_nc)
test['native-country'] = test['native-country'].map(dict_nc)

In [139]:
train['native-country'].unique()

array([25,  8,  5, 10, 28, 24, 33, 12, 19, 37, 13, 15, 11, 26, 16,  4, 42,
        2, 31, 21,  7, 43, 30, 22, 36,  0, 39, 35, 32,  9], dtype=int64)

In [140]:
test['native-country'].unique()

array([25, 10, 16, 24,  5, 37, 43, 28,  2, 22, 42, 13, 33,  4, 26, 31, 11,
       35, 15, 19, 30, 39,  8, 36,  7,  0, 12,  9, 21, 32], dtype=int64)

In [155]:
train.corr()

age  workclass    fnlwgt  education  education-num  \
age             1.000000   0.164381 -0.075753   0.110976       0.035084   
workclass       0.164381   1.000000 -0.029410   0.162631       0.143107   
fnlwgt         -0.075753  -0.029410  1.000000  -0.021721      -0.030600   
education       0.110976   0.162631 -0.021721   1.000000       0.908433   
education-num   0.035084   0.143107 -0.030600   0.908433       1.000000   
marital-status  0.345511   0.145659 -0.026239   0.121604       0.082381   
occupation      0.122510   0.199151 -0.010293   0.505764       0.478089   
relationship    0.362711   0.148109 -0.027490   0.149016       0.108102   
race            0.030967   0.021408 -0.096260   0.094781       0.089576   
sex             0.083999   0.088980  0.029929   0.047013       0.017029   
capital-gain    0.078498   0.098415 -0.005051   0.169546       0.127651   
capital-loss    0.054413   0.044133 -0.001513   0.095937       0.083925   
hours-per-week  0.073100   0.138940 -0.010154   0.168649       0.147569   
native-country  0.053992   0.048994 -0.107839   0.151892       0.235975   
income          0.238460   0.165266 -0.002994   0.365031       0.331798   

                marital-status  occupation  relationship      race       sex  \
age                   0.345511    0.122510      0.362711  0.030967  0.083999   
workclass             0.145659    0.199151      0.148109  0.021408  0.088980   
fnlwgt               -0.026239   -0.010293     -0.027490 -0.096260  0.029929   
education             0.121604    0.505764      0.149016  0.094781  0.047013   
education-num         0.082381    0.478089      0.108102  0.089576  0.017029   
marital-status        1.000000    0.189894      0.969115  0.126852  0.417371   
occupation            0.189894    1.000000      0.211716  0.106576  0.103936   
relationship          0.969115    0.211716      1.000000  0.128734  0.419588   
race                  0.126852    0.106576      0.128734  1.000000  0.112482   
sex                   0.417371    0.103936      0.419588  0.112482  1.000000   
capital-gain          0.084616    0.111829      0.087786  0.021237  0.050664   
capital-loss          0.071447    0.074087      0.077228  0.021638  0.042925   
hours-per-week        0.224070    0.210623      0.242891  0.046758  0.231437   
native-country        0.022363    0.119461      0.030623  0.054859  0.002202   
income                0.448346    0.349134      0.454753  0.101373  0.215613   

                capital-gain  capital-loss  hours-per-week  native-country  \
age                 0.078498      0.054413        0.073100        0.053992   
workclass           0.098415      0.044133        0.138940        0.048994   
fnlwgt             -0.005051     -0.001513       -0.010154       -0.107839   
education           0.169546      0.095937        0.168649        0.151892   
education-num       0.127651      0.083925        0.147569        0.235975   
marital-status      0.084616      0.071447        0.224070        0.022363   
occupation          0.111829      0.074087        0.210623        0.119461   
relationship        0.087786      0.077228        0.242891        0.030623   
race                0.021237      0.021638        0.046758        0.054859   
sex                 0.050664      0.042925        0.231437        0.002202   
capital-gain        1.000000     -0.031401        0.088609        0.027366   
capital-loss       -0.031401      1.000000        0.055271        0.017938   
hours-per-week      0.088609      0.055271        1.000000        0.017960   
native-country      0.027366      0.017938        0.017960        1.000000   
income              0.221387      0.135645        0.231045        0.100775   

                  income  
age             0.238460  
workclass       0.165266  
fnlwgt         -0.002994  
education       0.365031  
education-num   0.331798  
marital-status  0.448346  
occupation      0.349134  
relationship    0.454753  
race            0.101373  
sex             0.21

In [156]:
train['wcXhpw'] = train['workclass'] * train['hours-per-week']
test['wcXhpw'] = test['workclass'] * test['hours-per-week']

In [157]:
train['rXs'] = train['race'] * train['sex']
test['rXs'] = test['race'] * test['sex']

In [158]:
train['msXs'] = train['marital-status'] * train['sex']
test['msXs'] = test['marital-status'] * test['sex']

In [159]:
train['cgXcl'] = train['capital-gain'] * train['capital-loss']
test['cgXcl'] = test['capital-gain'] * test['capital-loss']

In [160]:
train.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income', 'wcXhpw', 'rXs', 'msXs', 'cgXcl'],
      dtype='object')

In [161]:
# X_train = train.loc[:,:'native-country']
X_train = train[['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'wcXhpw', 'rXs', 'msXs', 'cgXcl']]
# X_train = train[['age', 'workclass', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country']]
# X_train = train[['age', 'workclass', 'education-num','education', 'marital-status', 'occupation', 'relationship', 'race', 'sex',
#                 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country']]
y_train = train['income']
X_test = test
# X_test = test[['age', 'workclass', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country']]
# X_test = test[['age', 'workclass', 'education-num','education', 'marital-status', 'occupation', 'relationship', 'race', 'sex',
#                'capital-gain', 'capital-loss', 'hours-per-week', 'native-country']]

In [162]:
print("훈련용 문제 :",X_train.shape)
print("훈련용 문제 :",y_train.shape)
print("데스트용 문제 :",X_test.shape)

훈련용 문제 : (29305, 18)
훈련용 문제 : (29305,)
데스트용 문제 : (19537, 18)


In [163]:
from sklearn.ensemble import GradientBoostingClassifier
import time
import warnings
warnings.filterwarnings('ignore')

In [177]:
gb = GradientBoostingClassifier(random_state=2, max_depth=5)
gb.fit(X_train, y_train)

res = cross_val_score(gb,X_train,y_train,cv=8)
res
res.mean()

# md=5 : 0.870636410168913


GradientBoostingClassifier(max_depth=5, random_state=2)

array([0.87117904, 0.87223587, 0.87742288, 0.87196287, 0.87141687,
       0.86704887, 0.86786787, 0.87059787])

0.871216517231801

In [178]:
pred = gb.predict(X_test)
result = pd.read_csv("./data/sample_submission.csv")
result
result['income'] = pred
result.to_csv('./data/phy12.csv', index=False)

# 0.87253

no  income
0      29306       0
1      29307       0
2      29308       0
3      29309       0
4      29310       0
...      ...     ...
19532  48838       1
19533  48839       0
19534  48840       1
19535  48841       0
19536  48842       0

[19537 rows x 2 columns]

In [113]:
# !pip install xgboost

In [165]:
from xgboost import XGBClassifier

In [173]:
xgb_model = XGBClassifier(n_estimators=280, learning_rate=0.1, max_depth=4)
xgb_model.fit(X_train, y_train)
res = cross_val_score(xgb_model,X_train,y_train, cv=4)
res.mean()
# cv=8
# 200 : 0.8714896199544125
# 400, 0.1, 4 : 0.8717966614391287
# 400, 0.1, 3 : 0.8723426061035232

# 0.8727521344538266
# 3, 4  : 0.8714895087899046
# 4,4 : 0.871899004541969
# 4,6 : 0.8719330850344157

# 0.8728544909289997  280, 0.05

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=280, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

0.8706364295111395

In [131]:
# 7 : 0.8706704646963389
# 0.8704316135061223
res

# [0.87145197, 0.87087087, 0.87714988, 0.87387387, 0.87196287, 0.87332787, 0.87114387, 0.87223587]

array([0.87363537, 0.87223587, 0.87933388, 0.87114387, 0.87087087,
       0.87387387, 0.86977887, 0.87196287])

In [136]:
# 0.8693055991432084

pred = xgb_model.predict(X_test)
result = pd.read_csv("./data/sample_submission.csv")
result
result['income'] = pred
result.to_csv('./data/phy11.csv', index=False)


no  income
0      29306       0
1      29307       0
2      29308       0
3      29309       0
4      29310       0
...      ...     ...
19532  48838       1
19533  48839       0
19534  48840       1
19535  48841       0
19536  48842       0

[19537 rows x 2 columns]

In [179]:
# random forest 모델 불러오기
from sklearn.ensemble import RandomForestClassifier

In [180]:
forest_model = RandomForestClassifier(n_estimators=100,random_state=10)

In [181]:
res = cross_val_score(forest_model,X_train,y_train,cv=9)
res.mean()

0.8582153447443591